# -*- coding: utf-8 -*-
"""Portada, resumen ejecutivo y secciones 1–5 del informe v3."""
from ctx import *


def run(c):
    P = PCA_; K = CL; S = ESP
    inf = T('T08a_q3rot_vs_resto_infraestructura').set_index('clave'); pil = T('T08b_q3rot_vs_resto_pilares').set_index('clave')
    aI = T('T10a_ajustado_infra'); aP = T('T10b_ajustado_pilares')
    # ---------------------------------------------------------------- portada
    add = c.add
    add(D.p_xml(D.run('CENTRO DE INVESTIGACIÓN', b=True, color=D.NAVY, sz=30), '<w:spacing w:before="900" w:after="60"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('OBSERVATORIO DEL DESARROLLO', b=True, color=D.NAVY, sz=30), '<w:spacing w:after="500"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('Informe técnico', color=D.GREY, sz=24), '<w:spacing w:before="700" w:after="200"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('Perfiles cantonales de desarrollo, competitividad y seguridad en Costa Rica', b=True, sz=34), '<w:spacing w:after="160"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('Análisis exploratorio de 82 cantones con datos de 2022 a 2025', color=D.GREY, sz=26), '<w:spacing w:after="700"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('MSc. Agustín Gómez Meléndez', b=True, sz=24), '<w:spacing w:before="900" w:after="40"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('Investigador', i=True, color=D.GREY, sz=22), '<w:spacing w:after="40"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('2 de octubre de 2026', color=D.GREY, sz=22), '<w:spacing w:after="200"/><w:jc w:val="center"/>'))
    add(D.p_xml(D.run('Documento de trabajo — versión 3, revisión mayor tras evaluación metodológica externa', i=True, color=D.GREY, sz=18),
                '<w:spacing w:before="900"/><w:jc w:val="center"/>'))
    add(f'<w:p {D.NS}><w:pPr><w:rPr>{D.LANG}</w:rPr><w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1350" w:bottom="1440" w:left="1350" '
        f'w:header="708" w:footer="708" w:gutter="0"/><w:cols w:space="720"/><w:docGrid w:linePitch="360"/></w:sectPr></w:pPr></w:p>')
    # ---------------------------------------------------------------- contenido (marcador)
    c.toc_index = len(c.B.xml)
    add('<!--TOC-->')
    # ---------------------------------------------------------------- resumen ejecutivo
    c.h1('Resumen ejecutivo', pb=True)
    R = lambda t: add(D.body_italic(t))
    R('Costa Rica carece de una lectura conjunta de cómo se relacionan el desarrollo económico y la seguridad en sus cantones. Los diagnósticos disponibles suelen tratarlos por separado y asumen que se mueven en la misma dirección. Este informe examina esa premisa de forma exploratoria, como insumo para orientar diagnósticos territoriales posteriores y no como evaluación de desempeño de los cantones ni como base de asignación de recursos.')
    R(f'Se integran cuatro fuentes —PNUD, Escuela de Economía de la UCR y dos series del BCCR— en siete variables para los 82 cantones con datos completos, con años de observación entre 2022 y 2025 ({TN("fuentes")}). El diseño es transversal y descriptivo. Las asociaciones no establecen causalidad; los 82 cantones constituyen un censo y no una muestra aleatoria, de modo que los valores p, los intervalos de confianza y las tasas de descubrimiento falso (FDR) se interpretan como medidas de estabilidad de los patrones frente al remuestreo y al ajuste, no como inferencia a una población mayor.')
    R(f'Las siete variables se resumen en dos dimensiones que explican {num(P["var12"],1)}% de la varianza: una económico-empresarial ({num(P["pct_rot_econ"],1)}% tras la rotación) y otra de seguridad ciudadana ({num(P["pct_rot_sec"],1)}%). La primera es sólida (λ₁ = {num(P["eig1"],2)}, muy por encima del análisis paralelo). La segunda debe tratarse como exploratoria: su autovalor ({num(P["eig2"],2)}) supera el criterio de Kaiser y la media del análisis paralelo (1,25), pero queda por debajo de su percentil 95 (1,36), y descansa sobre todo en el par ISC–IVDAC (r = −0,78). Las cargas son estables ante el remuestreo (congruencia de Tucker mediana ≥ {num(P["tucker_sec_med"],2)}).')
    R(f'Al cruzar los puntajes rotados de ambas dimensiones, cada cantón se ubica en uno de cuatro perfiles definidos de forma relativa —por encima o por debajo del promedio de los 82 cantones—: Q1 (n = {P["n_q_rot"]["Q1"]}), Q2 ({P["n_q_rot"]["Q2"]}), Q3 ({P["n_q_rot"]["Q3"]}) y Q4 ({P["n_q_rot"]["Q4"]}). La versión anterior clasificaba con puntajes sin rotar, incongruentes con la interpretación de los ejes rotados; al corregirlo, {P["n_cambian"]} de los 82 cantones cambian de cuadrante, y {P["n_frontera"]} se ubican a menos de 0,25 desviaciones estándar de algún umbral, por lo que la pertenencia individual debe leerse como probabilística (probabilidad media de pertenencia por remuestreo: {num(P["prob_media"],2)}; {P["n_inestables_60"]} cantones por debajo de 0,60). El cuadrante Q3, por debajo del promedio en ambas dimensiones, agrupa 23 cantones periféricos que ocupan {pct(S["pct_area_q"]["Q3"])} del territorio y {pct(S["pct_pob_q"]["Q3"])} de la población de la muestra.')
    R(f'El agrupamiento K-means (k = 4) no corrobora esa partición: la separación entre grupos es débil (silhouette {num(K["sil_k4_best"],2)}), es menor que con k = 2 o 3, y la concordancia con los cuadrantes es moderada (ARI = {num(K["ari_q_km"],2)}; NMI = {num(K["nmi_q_km"],2)}). Se interpreta como ejercicio exploratorio complementario y no como validación.')
    r_pav = inf.loc['Red_vial_pavimentada_pct']; r_cal = aI.iloc[3]; r_net = aI.iloc[4]
    R(f'Frente al resto del país, Q3 presenta valores medianos inferiores en pavimentación vial, sucursales financieras por km², electricidad por km² y gasto vial municipal, y en los siete pilares del ICC (todos con q < 0,05). Sin embargo, esos indicadores de infraestructura son, en esencia, medidas de densidad territorial (ρ de Spearman con el logaritmo de la densidad poblacional entre 0,62 y 0,99, salvo en la conectividad móvil): al ajustar por densidad y región, las brechas de pavimentación, sucursales, electricidad y gasto vial se aproximan a cero (−0,12 a 0,19 desviaciones estándar) y solo persisten con claridad una mayor proporción de llamadas completadas (+{num(r_cal.beta_sem,2)} DE; q = {num(r_cal.q_sem,3)}) y, de forma sugestiva pero no robusta, un menor acceso a Internet ({num(r_net.beta_sem,2)} DE; q = {num(r_net.q_sem,3)}) y menores pilares Económico y de Gobierno (≈ −0,60 DE; q = {num(aP.iloc[0].q_sem,3)}). La cobertura móvil es estadísticamente equivalente entre grupos dentro de ±0,5 DE (TOST, p = {num(inf.loc["Cobertura_movil_pct"].p_tost,3)}).')
    pB = T('T11b_panelB_externo')
    R(f'Una vez eliminada la circularidad —construyendo el eje de seguridad sin la familia de variables que se le asocia—, los pilares Innovación, Calidad de vida e Infraestructura del ICC se asocian positivamente con el eje de seguridad (r = {num(pB.iloc[3].r,2)} a {num(pB.iloc[5].r,2)}), mientras que Económico, Empresarial y Laboral no muestran asociación. Entre los componentes del IVDAC, Demanda (r = {num(pB.iloc[8].r,2)}) y Manifestación de violencia ({num(pB.iloc[9].r,2)}) son los más asociados, con intervalos de confianza que se solapan: no puede afirmarse que uno pese más que el otro.')
    R(f'Los valores cantonales presentan fuerte dependencia espacial (I de Moran de {num(S["moran_E"],2)} para el eje económico y {num(S["moran_S"],2)} para el de seguridad; p < 0,001), de modo que los cantones no son observaciones independientes. Tras corregir por comparaciones múltiples, el análisis local identifica {S["lisa_E_fdr"]} agrupamientos en el eje económico (seis alto-alto en torno al Gran Área Metropolitana y uno bajo-bajo, Coto Brus) y ninguno en el eje de seguridad.')
    R(f'Un índice interno de rezago relativo de infraestructura normalizada, evaluado en {REZ["n_esc"]} escenarios, señala de forma estable a Talamanca, Matina, Hojancha, Buenos Aires y Coto Brus como casos para validación diagnóstica prioritaria dentro de Q3. El índice depende fuertemente de la ruralidad (ρ = {num(REZ["E0"]["rho82"],2)} con la densidad poblacional en los 82 cantones), por lo que identifica casos que verificar con indicadores físicos de acceso, no prioridades de intervención.')
    R(f'Las implicaciones son, por ello, de diagnóstico y no de asignación: validar con medidas físicas de acceso los cantones señalados; medir la conectividad con indicadores directos y no con puntajes normalizados; y abordar la seguridad con información desagregada sobre violencia y consumo, sin suponer que la actividad económica privada la explique. Las limitaciones se detallan en la sección 8 y los años de observación en la {TN("fuentes")}.')
    c.add(D.subhead('Acrónimos'))
    c.p('IDH: Índice de Desarrollo Humano (PNUD, 2024). ICC: Índice de Competitividad Cantonal (UCR, 2024), con siete pilares: económico, gobierno, empresarial, infraestructura, laboral, innovación y calidad de vida. PIB per cápita: Producto Interno Bruto cantonal por habitante (BCCR, 2022; denominador poblacional del ICC). UJ: Unidades Jurídicas por cada 1.000 habitantes (BCCR, 2024). ISC: Índice de Seguridad Ciudadana (PNUD, 2025; valores altos indican mejor seguridad). IPM: Índice de Pobreza Multidimensional (PNUD, 2024, corte único). IVDAC: Índice de Vulnerabilidad a Drogas y Actividades Conexas (PNUD, 2024; valores altos indican mayor vulnerabilidad) y sus cuatro componentes: oferta y tráfico, demanda, manifestación de violencia e institucional. PCA: análisis de componentes principales. DE: desviación estándar. FDR: tasa de descubrimiento falso (Benjamini–Hochberg); q es el valor p ajustado dentro de cada familia de contrastes. TOST: prueba de equivalencia por dos contrastes unilaterales. LISA: indicadores locales de asociación espacial. SEM: modelo de error espacial.')
    c.box('Nota de lectura:', 'el informe es descriptivo y exploratorio. «Por encima» o «por debajo» del promedio significa posición relativa respecto del promedio de los 82 cantones analizados, no cumplimiento de un estándar ni buen o mal desempeño. Las diferencias entre grupos se resumen con tamaños de efecto e intervalos de confianza; el valor q indica cuánto cambia la conclusión al considerar que se hicieron varias comparaciones a la vez.')

    # ---------------------------------------------------------------- 1. Antecedentes y alcance
    c.h1('1. Antecedentes y alcance', pb=True)
    c.p('El Centro de Investigación Observatorio del Desarrollo ha venido consolidando, a lo largo del 2026, un repositorio unificado de información cantonal de Costa Rica que integra cuatro familias de fuentes oficiales: el Índice de Desarrollo Humano y sus índices asociados del Programa de las Naciones Unidas para el Desarrollo (PNUD), el Índice de Competitividad Cantonal (ICC) de la Escuela de Economía de la Universidad de Costa Rica, el Producto Interno Bruto cantonal del Banco Central de Costa Rica (BCCR) y las estadísticas de Unidades Jurídicas del BCCR. Cada fuente fue documentada, validada y homologada frente al marco oficial de 84 cantones (Registro Nacional, División Territorial Administrativa 2026), quedando registradas las reglas de tratamiento de datos faltantes, los años efectivamente disponibles por variable y los escenarios de período común entre fuentes.')
    c.p('Este informe unifica los dos primeros ejercicios analíticos realizados sobre esa base de datos. El Ejercicio 1 explora, mediante correlación, componentes principales (PCA) y agrupamiento, la relación entre desarrollo humano, competitividad, producción económica y tejido empresarial a nivel cantonal, incorporando seguridad ciudadana, pobreza multidimensional y vulnerabilidad a drogas. El Ejercicio 2 profundiza en el cuadrante de menor posición relativa en ambos ejes (Q3), caracterizándolo con indicadores de infraestructura y conectividad, con los siete pilares del ICC y con los cuatro componentes del IVDAC.')
    c.p('Esta versión 3 incorpora los resultados de una evaluación metodológica externa que recomendó una revisión mayor. Las cifras, tablas y figuras fueron recalculadas íntegramente a partir de los paneles del repositorio; el formato y la estructura general del documento revisado se conservan, y las secciones de metodología se unificaron. La Tabla 1 resume los cambios sustantivos. El resultado más relevante es que varias conclusiones de la versión 2 dependían de la clasificación con puntajes sin rotar o de la interpretación de indicadores de densidad como indicadores de acceso, y se modifican en consecuencia.')
    c.h2('1.1 Cambios respecto de la versión 2')
    rows = [
        ['Puntajes para los cuadrantes', 'Puntajes sin rotar, interpretados con las cargas rotadas', f'Puntajes rotados calculados directamente, con signo orientado (ICC, ISC); {P["n_cambian"]} de 82 cantones cambian de cuadrante'],
        ['Autovalores', '4,10 y 1,343', f'{num(P["eig1"],3)} y {num(P["eig2"],3)} (PCA de correlación; los valores previos incluían el factor n/(n−1))'],
        ['Número de componentes', 'Criterio de Kaiser', 'Kaiser y análisis paralelo; el segundo componente se declara exploratorio'],
        ['Cuadrante Q3', '25 cantones; «franja costera y fronteriza»', '23 cantones (15 comunes con la v2); periferia rural, costera y fronteriza'],
        ['K-means', '«Confirma» la estructura; silhouette 0,244', f'Exploratorio; óptimo de 300 inicializaciones, silhouette {num(K["sil_k4_best"],3)}; k = 2 a 8, estabilidad y concordancia (ARI, NMI)'],
        ['Indicadores de infraestructura', 'Porcentajes y densidades físicas', 'Puntajes normalizados 0–100 del ICC; varios miden densidad territorial'],
        ['Brechas de Q3', 'Diferencia % de medias; p sin ajuste', 'Rank-biserial con IC bootstrap, q (FDR), TOST y ajuste por densidad y región (OLS HC3 y error espacial)'],
        ['Ejercicio 2 y circularidad', 'Pilares del ICC frente a un eje que incluye al ICC', 'Descomposición interna separada de la comparación externa (exclusión de un dominio a la vez)'],
        ['Dependencia espacial', 'No evaluada', 'I de Moran global, LISA con FDR, modelos de error espacial'],
        ['Cantones prioritarios', 'Cinco cantones de «prioridad de intervención»', f'Casos para validación diagnóstica; {REZ["n_esc"]} escenarios de sensibilidad'],
        ['Reproducibilidad', 'Código incluido en el cuerpo del documento', 'Ficha de reproducción (Apéndice A) y paquete reproducibilidad_v3/'],
    ]
    c.tabla('cambios', 'Cambios sustantivos entre la versión 2 y la versión 3.', ['Aspecto', 'Versión 2', 'Versión 3'], rows, [2100, 3000, 4800], ['left', 'left', 'left'], sz=17)

    # ---------------------------------------------------------------- 2. Justificación
    c.h1('2. Justificación')
    c.p('Costa Rica exhibe disparidades cantonales bien documentadas en desarrollo humano y desempeño económico, pero la evidencia sistemática sobre cómo se relacionan entre sí el desarrollo humano, la competitividad institucional-económica, la producción y el tejido empresarial —y cómo estas dimensiones interactúan con la seguridad ciudadana y la vulnerabilidad social— es dispersa, al estar cada índice publicado y documentado por instituciones distintas y sin un marco de análisis conjunto. Integrar estas fuentes en un solo ejercicio estadístico permite explorar patrones territoriales y evaluar su estabilidad. Un índice agregado —el ICC o el IVDAC— combina además componentes de naturaleza distinta (económica, institucional, de infraestructura, de criminalidad) que pueden pesar de forma muy desigual en la relación observada; sin desagregarlos, la lectura para la política pública queda genérica en lugar de accionable. Unir ambos ejercicios en un solo documento permite presentar, de forma trazable, tanto el hallazgo exploratorio agregado como su desagregación territorial y temática, insumo para el diagnóstico diferenciado por cantón y para la propia agenda de investigación del Observatorio.')

    # ---------------------------------------------------------------- 3. IA
    c.h1('3. Declaración de uso de inteligencia artificial')
    c.p('Este informe fue elaborado con apoyo de un asistente de inteligencia artificial (Claude, de Anthropic), utilizado para la limpieza y homologación de las bases de datos originales, la construcción de los paneles y datasets de análisis, la ejecución del análisis estadístico mediante scripts de Python desarrollados durante la sesión de trabajo, la generación de figuras y tablas, y la redacción de borradores del texto. En esta versión 3, el asistente se utilizó además para recalcular todas las cifras tras la evaluación externa (puntajes rotados, análisis paralelo, agrupamiento con selección de k, contrastes con control de comparaciones múltiples, dependencia espacial y análisis de sensibilidad), para reimplementar de forma independiente los cálculos centrales como verificación metodológica (Apéndice A) y para construir el paquete de reproducción. La definición de las preguntas de investigación, la selección de variables, los criterios metodológicos, la interpretación sustantiva de los resultados y la responsabilidad final sobre el contenido corresponden al investigador autor de este informe. La versión 2 incorporó una revisión editorial solicitada por Paola Omodeo Cubero (31 de agosto de 2026); la versión 3 responde a una evaluación metodológica externa y, a diferencia de la anterior, sí recalcula cifras, tablas y figuras. Los scripts, la lista de dependencias, las sumas de verificación de los archivos fuente y los resultados de referencia se entregan en la carpeta reproducibilidad_v3/.')

    # ---------------------------------------------------------------- 4. Preguntas y alcance inferencial
    c.h1('4. Preguntas de investigación y alcance inferencial')
    c.h2('4.1 Preguntas de investigación')
    c.p('*Ejercicio 1:* ¿Existe una asociación relevante entre el desarrollo humano, la competitividad cantonal, la producción económica y la densidad de tejido empresarial en los cantones de Costa Rica, y en qué medida la seguridad ciudadana, la pobreza multidimensional y la vulnerabilidad a drogas ayudan a describir los patrones territoriales que emergen de esa relación?')
    c.p('Preguntas secundarias del Ejercicio 1: (i) ¿la estructura de relaciones entre estas variables se describe mejor con una sola dimensión subyacente o con varias?; (ii) ¿es posible clasificar a los cantones en un número reducido de grupos territorialmente interpretables, y cuán estables son esa clasificación y la pertenencia de cada cantón?')
    c.p('*Ejercicio 2:* ¿Qué indicadores de infraestructura, conectividad y gobernanza, y qué componentes de vulnerabilidad a drogas, distinguen al cuadrante de menor posición relativa en ambos ejes (Q3) del resto de los cantones, y cuáles de esas diferencias persisten al considerar la densidad territorial, la región y la dependencia espacial?')
    c.p('Preguntas secundarias del Ejercicio 2: (i) ¿las diferencias de Q3 se extienden a toda la infraestructura o se concentran en algunos indicadores?; (ii) ¿qué pilares del ICC y componentes del IVDAC se asocian con el eje de seguridad cuando se evita que el eje incluya a la variable que se le compara?; (iii) ¿qué cantones de Q3 muestran de forma estable el mayor rezago relativo y ameritan validación diagnóstica con indicadores físicos?')
    c.h2('4.2 Alcance inferencial')
    c.bl([
        '**Descriptivo y exploratorio.** Los 82 cantones son la población completa con datos en las cuatro fuentes (un censo). No se infiere a una población mayor; los valores p y los intervalos de confianza describen la estabilidad de los resultados ante remuestreo, ajuste y comparaciones múltiples, no probabilidades de error poblacional.',
        '**Sin causalidad.** El diseño es transversal. Ningún resultado establece dirección ni mecanismo causal.',
        '**Dependencia espacial.** Los cantones vecinos se parecen entre sí; las observaciones no son independientes. Los valores p de las pruebas que asumen independencia se complementan con modelos de error espacial y con pruebas de permutación espacial.',
        '**Familias de hipótesis.** El control de comparaciones múltiples (Benjamini–Hochberg) se aplica dentro de familias definidas de antemano: F1, 21 correlaciones entre las siete variables; F2, 8 indicadores de infraestructura y conectividad; F3, 7 pilares del ICC; F4, componentes del eje de seguridad (panel A, 11; panel B, 7 y 4); F5, 28 variables para la I de Moran; y LISA, 82 cantones por eje.',
        '**Unidad de análisis.** Cantones; las conclusiones no se trasladan a personas u hogares (falacia ecológica). Se reportan estimaciones no ponderadas y ponderadas por población.',
    ])

    # ---------------------------------------------------------------- 5. Datos y métodos
    c.h1('5. Datos y métodos')
    c.h2('5.1 Diseño, fuentes y años de observación')
    c.p('Los análisis se enmarcan en el protocolo de trabajo del CIOdD para el uso de la base cantonal (manual de uso interno del repositorio), que exige declarar el año real de cada variable y el número efectivo de cantones cubiertos, en lugar de asumir que todas las fuentes cubren los mismos 84 cantones o el mismo año. Se optó por un diseño de corte transversal en el que cada variable entra en su último año efectivamente disponible (entre 2022 y 2025), sin forzar la coincidencia en un mismo año calendario; la consecuencia, que se evalúa mediante escenarios de año común (sección 6.4), es que las variables no son estrictamente contemporáneas. La muestra final es de 82 de los 84 cantones porque el ICC, la fuente más restrictiva, no cubre Monteverde ni Puerto Jiménez. En ninguna de las variables utilizadas hay valores faltantes dentro de esos 82 cantones.')
    rows = [
        ['IDH', 'PNUD, Atlas de Desarrollo Humano Cantonal 2026', '2024', 'Índice 0–1', '82'],
        ['ICC', 'UCR, Escuela de Economía, ICC 2023-2024', '2024', 'Índice 0–100', '82'],
        ['PIB per cápita', 'BCCR, PIB cantonal 2019-2022 (ed. 2023); denominador: población del ICC', '2022 (PIB) / 2024 (población)', 'Millones de colones por habitante', '82'],
        ['UJ por 1.000 hab.', 'BCCR, Estadísticas de Unidades Jurídicas 2005-2024 (ed. 2025); denominador: población del ICC', '2024', 'Unidades por 1.000 hab.', '82'],
        ['ISC', 'PNUD, Atlas 2026', '2025', 'Índice 0–1 (mayor = más seguridad)', '82'],
        ['IPM', 'PNUD, Atlas 2026', '2024 (corte único)', 'Proporción 0–1', '82'],
        ['IVDAC y 4 componentes', 'PNUD, Atlas 2026', '2024', 'Índice 0–1 (mayor = más vulnerabilidad)', '82'],
        ['7 pilares del ICC', 'UCR, ICC 2023-2024', '2024', 'Puntaje 0–100', '82'],
        ['8 indicadores de infraestructura y conectividad', 'UCR, ICC 2023-2024 (variables base)', '2023-2024 (según indicador)', 'Puntaje normalizado 0–100 del ICC (min–max); 2 con logaritmo previo', '82'],
        ['Densidad poblacional, área, región', 'ICC (población 2024); Registro Nacional (área); BCCR (regiones)', '2024', 'hab./km²; km²; 6 regiones BCCR', '82'],
    ]
    c.tabla('fuentes', 'Variables, fuentes, ediciones citadas, años de observación y cobertura. El «año de observación» es el del dato; la «edición» es la publicación citada en la Bibliografía. La fecha exacta de descarga de cada archivo no quedó registrada en los metadatos del repositorio; en su lugar se registran las sumas de verificación SHA-256 de los archivos fuente (Anexo E).',
            ['Variable', 'Fuente y edición', 'Año de observación', 'Unidad o escala', 'n'], rows, [1750, 3600, 1700, 2350, 500], ['left', 'left', 'center', 'left', 'center'], sz=16)
    c.h2('5.2 Medición y tratamiento de los datos')
    c.p('**Indicadores de infraestructura.** Los ocho indicadores base de infraestructura y conectividad provienen de la hoja de variables del ICC, en la que cada uno figura como puntaje normalizado de 0 a 100 («Norm.»). No son porcentajes físicos ni tasas en unidades comparables: por ejemplo, «red vial cantonal pavimentada» es el puntaje normalizado de la proporción de red pavimentada, y los indicadores de electricidad y de gasto vial se transformaron con logaritmo antes de normalizarse. Las etiquetas de la versión 2 que sugerían porcentajes directos se corrigen. Varios de estos indicadores miden en realidad densidad por unidad de superficie (sucursales financieras por km², viviendas con electricidad por km²); la densidad territorial no es acceso y, por ello, se examina su dependencia de la densidad poblacional (sección 5.6).')
    c.p('**Denominadores y años.** El PIB per cápita de 2022 se divide por la población del ICC de 2024. El ICC publica también la población de 2023, y ambas series difieren (5,26 millones frente a 5,15 millones para los mismos cantones; razón cantonal entre 0,81 y 1,12) por corresponder a distintas ediciones de proyección; la población de 2022 no está en el repositorio. Los resultados se contrastan con un escenario que usa la población de 2023 (correlación del PIB per cápita entre ambas versiones: 0,999) y con una ventana común 2022–2023. En consecuencia, el PIB per cápita y las unidades jurídicas por habitante son medidas aproximadas, afectadas por el desajuste entre numerador y denominador.')
    c.p('**Transformaciones y estandarización.** Las variables se estandarizan (media 0, desviación estándar muestral) antes del PCA, que se calcula sobre la matriz de correlación. Para evaluar la sensibilidad a asimetría y valores extremos se reproduce el análisis con el logaritmo del PIB per cápita, con transformación de rangos a normal, con winsorización 5/95 y con escalado robusto (mediana/MAD).')
    c.h2('5.3 Estadística descriptiva y correlación')
    c.p('Se reportan media, desviación estándar, mediana, cuartiles, asimetría, curtosis y coeficiente de variación, y se identifican valores extremos con el criterio de Tukey. Para los 21 pares entre las siete variables se calcula la correlación de Pearson con intervalo de confianza de Fisher y, como contraste de robustez frente a asimetría, la de Spearman con intervalo bootstrap percentil (5.000 remuestreos); el valor p de ambas se ajusta por FDR en la familia F1. El umbral de relevancia |r| ≥ 0,30 se conserva como criterio descriptivo acordado, pero la lectura se apoya en el intervalo de confianza y en q.')
    c.h2('5.4 Componentes principales, rotación y cuadrantes')
    c.p('La adecuación del PCA se evalúa con la medida de Kaiser–Meyer–Olkin y la prueba de esfericidad de Bartlett. El número de componentes se decide con tres criterios: autovalor mayor que 1 (Kaiser), análisis paralelo de Horn con datos normales y con permutación de columnas (2.000 iteraciones, percentil 95) y la interpretabilidad. Los dos componentes retenidos se rotan con varimax (con normalización de Kaiser).')
    c.p('Los puntajes de cada cantón se calculan **directamente en el espacio rotado**: S_{rot} = Z V Λ^{-1/2} R, con la misma matriz de rotación R que transforma las cargas (L_{rot} = L R), de modo que ejes, cargas y cuadrantes son mutuamente consistentes. El signo de cada eje se orienta con una variable de referencia declarada: el eje económico-empresarial tiene signo positivo en el ICC y el eje de seguridad, signo positivo en el ISC (valores altos = mejor seguridad). Los cuadrantes se definen por el signo de los puntajes rotados —Q1: E ≥ 0 y S ≥ 0; Q2: E < 0 y S ≥ 0; Q3: E < 0 y S < 0; Q4: E ≥ 0 y S < 0—, es decir, por la posición **relativa respecto del promedio de los 82 cantones** (los puntajes están centrados en cero), sin connotación de buen o mal desempeño. Se informan las cargas rotadas completas y las comunalidades, y no solo la carga del IDH.')
    c.p('La estabilidad se evalúa con: bootstrap de 2.000 remuestras (congruencia de Tucker de las cargas, varianza explicada), exclusión de un cantón a la vez, probabilidad de pertenencia a cada cuadrante por proyección de 1.000 soluciones bootstrap, identificación de cantones frontera (|puntaje| < 0,25 respecto de algún umbral) y siete escenarios de sensibilidad (S1–S7: logaritmo del PIB, rangos a normal, winsorización, logaritmo de variables asimétricas, exclusión de los cinco cantones extremos, población 2023 y ventana 2022–2023). La concordancia entre clasificaciones se mide con el índice de Rand ajustado (ARI), la información mutua normalizada (NMI) y el índice de Jaccard.')
    c.h2('5.5 Agrupamiento exploratorio')
    c.p('Se aplica K-means (distancia euclídea sobre las siete variables estandarizadas) con k de 2 a 8, evaluando silhouette, Calinski–Harabasz y Davies–Bouldin, y la estabilidad por remuestreo (índice de Jaccard medio por grupo, 400 remuestras). Dado que la solución depende de la inicialización, se conserva el mejor resultado de 300 inicializaciones. Se repite el procedimiento con las cinco transformaciones de la sección 5.2 y se contrasta con un agrupamiento jerárquico de enlace promedio sobre la distancia de Gower. La concordancia con los cuadrantes se mide con ARI y NMI, y su significación con una prueba de permutación (9.999). K-means asume grupos esféricos y de varianza similar, supuestos que los datos no cumplen con claridad; por ello se trata como exploratorio.')
    c.h2('5.6 Comparación de Q3 con el resto: contrastes, equivalencia, ajuste y circularidad')
    c.p('Para cada indicador se compara Q3 (cuadrante rotado, n = 23) con el resto (n = 59) mediante la U de Mann–Whitney. Se reportan las medianas y el rango intercuartílico de cada grupo, el desplazamiento de Hodges–Lehmann, el coeficiente rank-biserial como tamaño de efecto y la d de Cohen estandarizada, con intervalos de confianza bootstrap percentil del 95% (5.000 remuestreos). Los valores p se ajustan por FDR dentro de F2 (8 indicadores) y F3 (7 pilares). Para afirmar similitud entre grupos se usa una prueba de equivalencia (TOST) con margen de ±0,5 desviaciones estándar; un valor p mayor que 0,05 en la prueba de diferencias no se interpreta como equivalencia.')
    c.p('Dado que los indicadores de infraestructura dependen de la densidad, se calcula la correlación de Spearman de cada uno con el logaritmo de la densidad poblacional y se estima, para cada indicador estandarizado, un modelo con la pertenencia a Q3, el logaritmo de la densidad y la región del BCCR como regresores, con errores robustos HC3 y, para tratar la dependencia espacial, con un modelo de error espacial estimado por máxima verosimilitud sobre la matriz de contigüidad. El coeficiente de Q3 se expresa en desviaciones estándar del indicador. Para evitar diferencias porcentuales sobre valores ya transformados o normalizados, ya no se calculan diferencias porcentuales de medias. Se comparan además las estimaciones no ponderadas y ponderadas por población.')
    c.p('**Circularidad.** Los pilares del ICC y los componentes del IVDAC integran los índices que forman los ejes. Por ello se distinguen dos usos: (A) la descomposición interna del eje de seguridad (correlación del eje completo con los pilares y componentes), que es descriptiva y no constituye una prueba independiente, y (B) la comparación externa, con el eje reconstruido **sin** la familia analizada (sin ICC al evaluar los pilares; sin IVDAC al evaluar sus componentes). Además, se repite el contraste de Q3 definiendo los cuadrantes sin el ICC, sin el IVDAC y sin el ISC (exclusión de un dominio a la vez).')
    c.h2('5.7 Dependencia espacial')
    c.p('Se construye una matriz de vecindad por contigüidad de tipo reina a partir de los 84 polígonos del marco cantonal (OCHA/HDX, COD-AB), restringida a los 82 cantones y estandarizada por filas; el promedio es de 5,4 vecinos por cantón y no hay cantones aislados. Se calcula la I de Moran global con inferencia por permutación (9.999) para las variables y ejes, con FDR en F5; los indicadores locales de asociación espacial (LISA) con permutación y FDR en cada eje (82 pruebas); y el conteo de uniones (join counts) para la pertenencia a Q3. El mapa se usa como apoyo visual; los límites no coinciden exactamente con la división territorial 2026.')
    c.h2('5.8 Índice de rezago relativo y análisis de sensibilidad')
    c.p('El índice interno de rezago relativo es el promedio, con signo invertido, de los ocho indicadores estandarizados (a mayor valor, menor dotación normalizada relativa). Su estabilidad se evalúa en 13 escenarios: pesos iguales (E0), exclusión de las dos densidades por km² (E1), ponderación por el primer componente principal (E2), estandarización robusta (E3), exclusión de cada indicador (8 escenarios) y exclusión del indicador de Internet de ENAHO (E4). Se reportan los rangos mínimo, mediano y máximo de cada cantón dentro de Q3, el porcentaje de escenarios en que cae entre los cinco primeros, la correlación de rangos de Kendall con E0 y la correlación del índice con la densidad poblacional.')
    c.h2('5.9 Software y reproducibilidad')
    c.p('Todo el procesamiento se ejecutó en Python 3.13 (NumPy, pandas, SciPy, scikit-learn, statsmodels, factor_analyzer, libpysal, esda, spreg, GeoPandas), con semilla fija y versiones registradas en el Apéndice A. El código no se incluye en el cuerpo de este documento: se entrega en el paquete reproducibilidad_v3/ junto con una ficha de reproducción. Se distinguen dos controles: la **verificación de reproducción** (el código vuelve a producir las mismas tablas) y la **validación metodológica independiente** (los cálculos centrales se reimplementan desde cero y se comparan con las librerías).')
