# -*- coding: utf-8 -*-
"""Sección 6 (resultados) del informe v3."""
from ctx import *

NOM = {'Q1': 'Q1 · E+ / S+', 'Q2': 'Q2 · E− / S+', 'Q3': 'Q3 · E− / S−', 'Q4': 'Q4 · E+ / S−'}


def run(c):
    P = PCA_; K = CL; S = ESP; EJ = EJ2
    m = pd.read_csv(f'{DAT}/base82_con_ejes.csv')
    c.h1('6. Resultados', pb=True)
    # ------------------------------------------------------------ 6.1
    c.h2('6.1 Estadística descriptiva')
    d = T('T01_descriptivos'); ex = T('T01b_extremos_tukey')
    rows = [[r.variable, num(r.media, 3 if r.media < 1 else 2), num(r.de, 3 if r.de < 1 else 2), num(r.mediana, 3 if r.mediana < 1 else 2),
             f'{num(r.q1, 3 if r.q1 < 1 else 2)}–{num(r.q3, 3 if r.q3 < 1 else 2)}', f'{num(r.minimo, 3 if r.minimo < 1 else 2)}–{num(r.maximo, 3 if r.maximo < 1 else 2)}',
             num(r.asimetria, 2), num(r.cv_pct, 1)] for r in d.itertuples()]
    c.p(f'El IDH es la variable más homogénea entre cantones (coeficiente de variación de {num(d.cv_pct[0],1)}%). En el otro extremo, el PIB per cápita es extremadamente asimétrico (asimetría = {num(d.asimetria[2],1)}; CV = {num(d.cv_pct[2],0)}%): {int(ex.n_extremos_tukey[2])} cantones superan el límite superior de Tukey, y San José, Escazú, Santa Ana, Montes de Oca y Belén concentran los valores extremos tanto del PIB per cápita como de las unidades jurídicas por habitante. Esa asimetría hace que los estadísticos basados en medias y la correlación de Pearson sean sensibles a pocos cantones, por lo que se acompañan con estimaciones robustas (sección 6.2) y análisis de sensibilidad (sección 6.4). Solo el IDH (p = {num(d.shapiro_p[0],3)}) es compatible con la normalidad (prueba de Shapiro–Wilk); el resto se desvía de ella.')
    c.tabla('descr', 'Estadísticos descriptivos de las siete variables (n = 82 cantones; cada variable en su último año disponible). Q1–Q3: cuartiles. CV: coeficiente de variación.',
            ['Variable', 'Media', 'DE', 'Mediana', 'Q1–Q3', 'Mín–máx', 'Asim.', 'CV (%)'], rows, [2300, 900, 900, 1000, 1500, 1700, 700, 800],
            ['left'] + ['center'] * 7, sz=17)
    c.fig('distrib', 'fig01_distribuciones', 6.3, 'Distribución de las siete variables (n = 82 cantones, cada una en su último año disponible); cada punto es un cantón.')
    # ------------------------------------------------------------ 6.2
    c.h2('6.2 Correlación')
    cr = T('T02_correlaciones_21_pares')
    n17 = int((cr.r_pearson.abs() >= .30).sum()); nq = int((cr.q_fdr_pearson < .05).sum()); nqs = int((cr.q_fdr_spearman < .05).sum())
    c.p(f'De los 21 pares posibles, {n17} superan el umbral descriptivo |r| ≥ 0,30, todos con q < 0,05. En total, {nq} de los 21 coeficientes de Pearson y {nqs} de los de Spearman tienen q < 0,05; la única asociación sin respaldo en Pearson es PIB per cápita–ISC (r = {num(cr.r_pearson[20],2)}; q = {num(cr.q_fdr_pearson[20],2)}). La {TN("corr")} resume los diez pares más fuertes; los 21 pares figuran en el Anexo B. La asociación más intensa es la negativa entre ISC e IVDAC (r = {num(cr.r_pearson[0],2)}; IC 95% {num(cr.fisher_lo[0],2)} a {num(cr.fisher_hi[0],2)}), seguida de las asociaciones entre IDH e ICC y entre ICC y unidades jurídicas.')
    c.p(f'Las asociaciones que involucran al PIB per cápita son sensibles a los cantones extremos. Entre PIB y unidades jurídicas, la r de Pearson es {num(cr.r_pearson[5],2)}, con un intervalo bootstrap asimétrico ({num(cr.ic_lo[5],2)} a {num(cr.ic_hi[5],2)}), frente a ρ = {num(cr.rho_spearman[5],2)} de Spearman y r = {num(cr.r_pearson_logPIB[5],2)} con el logaritmo del PIB. Entre ICC y PIB, r = {num(cr.r_pearson[6],2)} con Pearson y {num(cr.r_pearson_logPIB[6],2)} con el logaritmo. Las asociaciones del PIB per cápita se interpretan, por tanto, con cautela: el signo es estable, pero la magnitud depende de pocos cantones.')
    top = cr.head(10)
    rows = [[f'{r.var1} — {r.var2}', num(r.r_pearson, 2), f'{num(r.fisher_lo,2)}; {num(r.fisher_hi,2)}', f'{num(r.ic_lo,2)}; {num(r.ic_hi,2)}', num(r.rho_spearman, 2), pf(r.q_fdr_pearson)] for r in top.itertuples()]
    c.tabla('corr', 'Diez correlaciones más fuertes entre las siete variables (n = 82; familia F1 de 21 pruebas). IC: intervalo de confianza del 95% (Fisher y bootstrap percentil, 5.000 remuestreos); q: valor p ajustado por FDR (Benjamini–Hochberg) para la correlación de Pearson.',
            ['Par de variables', 'r de Pearson', 'IC Fisher', 'IC bootstrap', 'ρ de Spearman', 'q (FDR)'], rows, [3700, 900, 1300, 1400, 1000, 900], sz=17)
    c.fig('corr', 'fig02_correlaciones', 4.9, 'Matriz de correlación entre las siete variables (n = 82): Pearson en el triángulo inferior y Spearman en el superior.')
    c.box('En términos sencillos:', 'un coeficiente de correlación (r) va de −1 a 1 y mide qué tan de la mano se mueven dos variables entre cantones: cerca de 1, cuando una sube la otra también sube casi siempre; cerca de −1, cuando una sube la otra baja casi siempre; cerca de 0, no hay un patrón claro. El resultado más fuerte (−0,78 entre seguridad ciudadana y vulnerabilidad a drogas) indica que los cantones con mejor seguridad ciudadana tienden, de forma consistente, a tener menor vulnerabilidad a las drogas. Que dos variables se muevan juntas no significa que una cause la otra.')
    # ------------------------------------------------------------ 6.3
    c.h2('6.3 Componentes principales')
    pa = T('T03b_autovalores_analisis_paralelo'); ld = T('T03c_cargas_comunalidades'); bt = T('T03d_cargas_bootstrap')
    c.p(f'La matriz de correlaciones es adecuada para el PCA (KMO global = {num(P["kmo_total"],3)}; prueba de esfericidad de Bartlett: χ² = {num(P["bartlett_chi2"],1)}, gl = 21, p < 0,001). Los autovalores de la matriz de correlación son {num(P["eig1"],3)} y {num(P["eig2"],3)}, que explican {num(P["var1"],1)}% y {num(P["var2"],1)}% de la varianza ({num(P["var12"],1)}% acumulado; intervalo bootstrap 95%: {num(P["var12_boot_lo"],1)}% a {num(P["var12_boot_hi"],1)}%). Los autovalores de 4,10 y 1,343 publicados en la versión anterior incluían el factor n/(n−1) por haber estandarizado con la desviación estándar poblacional; la proporción de varianza explicada no cambia.')
    c.p(f'El primer componente supera con holgura el análisis paralelo (percentil 95: {num(pa.PA_normal_p95[0],2)}). El segundo (λ₂ = {num(pa.autovalor[1],3)}) supera el criterio de Kaiser y la media del análisis paralelo ({num(pa.PA_normal_media[1],3)} con datos normales; {num(pa.PA_perm_media[1],3)} con permutación), pero queda ligeramente por debajo del percentil 95 ({num(pa.PA_normal_p95[1],3)} y {num(pa.PA_perm_p95[1],3)}). El segundo componente se considera, en consecuencia, una dimensión exploratoria y no un hallazgo establecido: es una solución plausible y estable en sus cargas, pero su existencia como dimensión separada depende del criterio de retención adoptado y descansa principalmente en el par ISC–IVDAC.')
    rows = [[r.componente, num(r.autovalor, 3), num(r.pct_varianza, 1), num(r.pct_acumulado, 1), num(r.PA_normal_media, 3), num(r.PA_normal_p95, 3), r.retener_Kaiser, r.retener_PA_p95] for r in pa.itertuples()]
    c.tabla('eig', 'Autovalores de la matriz de correlación, varianza explicada y análisis paralelo de Horn (2.000 iteraciones con datos normales; percentil 95). La permutación de columnas da resultados casi idénticos (Figura 3).',
            ['Componente', 'Autovalor', '% varianza', '% acumulado', 'AP: media', 'AP: p95', 'Kaiser (λ > 1)', 'AP p95'], rows, [1300, 1100, 1100, 1200, 1100, 1100, 1500, 1000], sz=17)
    c.fig('scree', 'fig03_scree_paralelo', 4.8, 'Gráfico de sedimentación con el análisis paralelo de Horn (datos normales y permutación de columnas).')
    rows = []
    for (r, b) in zip(ld.itertuples(), bt.itertuples()):
        rows.append([r.variable, num(r.C1_sin_rotar, 2), num(r.C2_sin_rotar, 2), num(r.Eje_economico_rot, 2), f'{num(b.ic_lo_econ,2)}; {num(b.ic_hi_econ,2)}',
                     num(r.Eje_seguridad_rot, 2), f'{num(b.ic_lo_seg,2)}; {num(b.ic_hi_seg,2)}', num(r.comunalidad, 2)])
    c.tabla('cargas', 'Cargas sin rotar y rotadas (varimax con normalización de Kaiser), intervalos bootstrap del 95% de las cargas rotadas (2.000 remuestras) y comunalidades. Eje económico-empresarial orientado con el ICC positivo; eje de seguridad orientado con el ISC positivo (valores altos = mejor seguridad). Varianza rotada: ' + f'{num(P["pct_rot_econ"],1)}% y {num(P["pct_rot_sec"],1)}%.',
            ['Variable', 'C1', 'C2', 'Eje econ.', 'IC 95%', 'Eje seg.', 'IC 95%', 'Comun.'], rows, [2350, 700, 700, 900, 1300, 900, 1300, 800], sz=17)
    c.p(f'Tras la rotación, el **eje económico-empresarial** reúne al ICC ({num(ld.Eje_economico_rot[1],2)}), las unidades jurídicas por habitante ({num(ld.Eje_economico_rot[3],2)}), el PIB per cápita ({num(ld.Eje_economico_rot[2],2)}) y, en menor medida, el IDH ({num(ld.Eje_economico_rot[0],2)}); el **eje de seguridad** reúne al ISC ({num(ld.Eje_seguridad_rot[4],2)}) y al IVDAC ({num(ld.Eje_seguridad_rot[6],2)}). El IDH carga de forma relevante en ambos ejes ({num(ld.Eje_economico_rot[0],2)} y {num(ld.Eje_seguridad_rot[0],2)}), pero **no es la única variable de carga cruzada**: el IPM carga −0,53 en ambos. Las comunalidades más bajas corresponden al IPM ({num(ld.comunalidad[5],2)}) y al PIB per cápita ({num(ld.comunalidad[2],2)}), es decir, las dos dimensiones recogen peor la variación de esas variables. La Tabla {TABS.index("cargas")+1} corrige la versión anterior, que reportaba solo la carga del IDH.')
    c.p(f'Los puntajes rotados se calcularon directamente. El puntaje de seguridad se correlaciona {num(P["r_eje_seg_directo_ISC"],3)} con el ISC (la reconstrucción por mínimos cuadrados usada en la versión 2 daba {num(P["r_eje_seg_v2_ISC"],3)}) y el puntaje económico, {num(P["r_eje_econ_directo_ICC"],3)} con el ICC. La estructura es estable ante el remuestreo: la congruencia de Tucker de las cargas bootstrap con las originales tiene mediana de {num(P["tucker_econ_med"],3)} (eje económico) y {num(P["tucker_sec_med"],3)} (eje de seguridad), con percentil 5 de {num(P["tucker_econ_p05"],3)} y {num(P["tucker_sec_p05"],3)}; al excluir un cantón a la vez, la congruencia mínima es {num(P["loo_tucker_min_econ"],3)} y {num(P["loo_tucker_min_seg"],3)}.')
    c.box('En términos sencillos:', 'el PCA busca pocos «ejes» que resuman lo que las siete variables tienen en común. Aquí aparecen dos: uno económico-empresarial y otro de seguridad. La rotación reordena los ejes sin perder información para que cada variable quede asociada, con la mayor claridad posible, a uno solo; aun así, el IDH y la pobreza multidimensional se reparten entre ambos. El segundo eje es una lectura razonable, pero menos firme que el primero: depende sobre todo de que el ISC y el IVDAC se muevan en sentido opuesto.')
    # ------------------------------------------------------------ 6.4
    c.h2('6.4 Cuadrantes con puntajes rotados y sensibilidad de la clasificación')
    q = T('T04b_cuadrantes_canton_por_canton'); tr = T('T04a_matriz_transicion'); pf_ = T('T12_perfil_cuadrantes_rotados')
    c.p(f'Con los puntajes rotados, la clasificación de los 82 cantones queda en Q1 = {P["n_q_rot"]["Q1"]}, Q2 = {P["n_q_rot"]["Q2"]}, Q3 = {P["n_q_rot"]["Q3"]} y Q4 = {P["n_q_rot"]["Q4"]}, frente a {P["n_q_orig"]["Q1"]}, {P["n_q_orig"]["Q2"]}, {P["n_q_orig"]["Q3"]} y {P["n_q_orig"]["Q4"]} con los puntajes sin rotar de la versión 2. Solo {num(P["pct_igual"],0)}% de los cantones conserva su cuadrante (ARI entre ambas clasificaciones = {num(P["ari_rot_vs_orig"],2)}; {P["n_cambian"]} cantones cambian). La {TN("trans")} muestra las transiciones: 15 de los 25 cantones del antiguo Q3 permanecen en Q3, mientras que diez pasan a Q4 (San Ramón, Orotina, Liberia, Nicoya, Santa Cruz, Abangares, Puntarenas, Osa, Quepos y Garabito); ocho cantones del antiguo Q2 ingresan a Q3 (Alajuelita, Upala, Los Chiles, Guatuso, Sarapiquí, Buenos Aires, Pococí y Guácimo). Los cantones Q4→Q1 (Escazú, Santa Ana, Montes de Oca, Curridabat, Cartago, Santo Domingo y Flores) y los 15 Q1→Q2 completan los cambios.')
    rows = [[NOM[r.iloc[0]] + ' (v2)' if False else r.iloc[0], *[int(x) for x in r.iloc[1:5]], int(r.iloc[1:5].sum())] for _, r in tr.iterrows()]
    rows.append(['Total (v3)'] + [P['n_q_rot'][k] for k in ['Q1', 'Q2', 'Q3', 'Q4']] + [82])
    c.tabla('trans', 'Matriz de transición entre el cuadrante de la versión 2 (puntajes sin rotar; filas) y el cuadrante con puntajes rotados (columnas). La diagonal (11 + 12 + 15 + 4 = 42 cantones) corresponde a los cantones que conservan su cuadrante.',
            ['Cuadrante v2 \\ cuadrante v3', 'Q1', 'Q2', 'Q3', 'Q4', 'Total'], rows, [3200, 1100, 1100, 1100, 1100, 1100], sz=18)
    c.p(f'Los cuadrantes son posiciones **relativas al promedio de los 82 cantones**: Q1 agrupa a 18 cantones por encima del promedio en ambos ejes (los del Gran Área Metropolitana oriental y occidental, como Escazú, Santa Ana, Moravia o Cartago); Q2, a 27 cantones por debajo del promedio económico y por encima del de seguridad (resto del Valle Central y zonas rurales de Alajuela y Cartago); Q4, a 14 cantones por encima del promedio económico y por debajo del de seguridad (San José, Alajuela, Heredia y Belén, y ciudades intermedias como Liberia, Nicoya, Santa Cruz, Puntarenas y Quepos); y Q3, a 23 cantones por debajo del promedio en ambos ejes: Alajuelita, Upala, Los Chiles, Guatuso, Turrialba, Sarapiquí, Bagaces, Carrillo, Cañas, La Cruz, Hojancha, Esparza, Buenos Aires, Golfito, Coto Brus, Parrita, Corredores, Limón, Pococí, Siquirres, Talamanca, Matina y Guácimo. Q3 incluye seis cantones de Puntarenas, seis de Limón, cinco de Guanacaste y tres de Alajuela, junto con Alajuelita, Turrialba y Sarapiquí; no es, por tanto, estrictamente una «franja costera y fronteriza», sino un conjunto de cantones periféricos y rurales.')
    rows = []
    for r in pf_.itertuples():
        rows.append([NOM[r.cuadrante], r.n, pct(r.pct_pob), pct(r.pct_area), num(r.IDH_2024_med, 3), num(r.ICC_2024_med, 1), num(r.PIB_percapita_2022_med, 1), num(r.UJ_por_1000hab_2024_med, 1),
                     num(r.ISC_2025_med, 3), num(r.IPM_2024_med, 3), num(r.IVDAC_2024_med, 3)])
    dd = T('T01_descriptivos'); mm = lambda i, dgt: num(dd.mediana[i], dgt)
    rows.append(['82 cantones', 82, '100%', '100%', mm(0, 3), mm(1, 1), mm(2, 1), mm(3, 1), mm(4, 3), mm(5, 3), mm(6, 3)])
    c.tabla('perfil', 'Perfil de los cuadrantes rotados: participación en la población y el área de los 82 cantones y mediana de cada variable (rango intercuartílico en el Anexo C). E+/E−: por encima/por debajo del promedio del eje económico-empresarial; S+/S−: ídem para el eje de seguridad.',
            ['Cuadrante', 'n', '% pob.', '% área', 'IDH', 'ICC', 'PIB pc', 'UJ/1.000', 'ISC', 'IPM', 'IVDAC'], rows, [1700, 450, 800, 800, 800, 800, 850, 900, 800, 800, 900], ['left'] + ['center'] * 10, sz=16, hl_rows=(2,))
    c.p(f'Q3 ocupa {pct(S["pct_area_q"]["Q3"])} del territorio con {pct(S["pct_pob_q"]["Q3"])} de la población de los 82 cantones, mientras que Q1 reúne {pct(S["pct_pob_q"]["Q1"])} de la población en {pct(S["pct_area_q"]["Q1"])} del área. Las medianas de Q3 son las más bajas del IDH ({num(pf_.IDH_2024_med[2],3)}), del ICC ({num(pf_.ICC_2024_med[2],1)}) y del ISC ({num(pf_.ISC_2025_med[2],3)}) y las más altas del IPM ({num(pf_.IPM_2024_med[2],3)}) y del IVDAC ({num(pf_.IVDAC_2024_med[2],3)}), lo que describe una posición relativa desfavorable pero no implica deterioro absoluto.')
    c.fig('plano', 'fig04_plano_ejes_rotados', 5.2, 'Cantones en el plano de los puntajes rotados (eje económico-empresarial y eje de seguridad), con los vectores de cargas de las siete variables.')
    c.fig('mapas', 'fig05_mapa_cuadrantes', 6.3, 'Cuadrantes cantonales con puntajes sin rotar (versión 2; izquierda) y con puntajes rotados (versión 3; derecha). Monteverde y Puerto Jiménez, sin cobertura del ICC, aparecen sin dato (sombreado). Límites administrativos: OCHA/HDX, COD-AB (división 2022); el mapa es ilustrativo y no reemplaza a la ' + TN('perfil') + ' como fuente de cifras.')
    c.box('En términos sencillos:', 'cada cantón queda ubicado por dos coordenadas —su posición en el eje económico y en el de seguridad— respecto del promedio de los 82 cantones. «Por encima» o «por debajo» describe solo esa posición relativa: un cantón en Q3 no está «mal», está por debajo del promedio de este conjunto en ambos ejes. Los límites entre cuadrantes son líneas arbitrarias en un continuo; por eso la pertenencia de un cantón cercano a una línea puede cambiar con pequeñas modificaciones del análisis.')
    c.p(f'**Estabilidad de la clasificación.** {P["n_frontera"]} cantones se ubican a menos de 0,25 desviaciones estándar de algún umbral. La probabilidad media de pertenencia al cuadrante asignado, estimada con 1.000 soluciones bootstrap, es de {num(P["prob_media"],2)}; {P["n_estables_80"]} cantones tienen probabilidad ≥ 0,80 y {P["n_inestables_60"]} tienen probabilidad < 0,60 (Pérez Zeledón, San Carlos, Upala y Orotina; Barva y Sarapiquí rondan 0,60). Al excluir un cantón a la vez cambian como máximo {P["loo_max_cambios"]} cantones (mediana: {num(P["loo_med_cambios"],0)}). La clasificación individual debe leerse, por tanto, como probabilística, con mayor certeza en los cantones lejanos a los umbrales (Anexo C).')
    sn = T('T05_sensibilidad_pca')
    rows = [[r.escenario.split(' · ')[0] + ' · ' + r.escenario.split(' · ')[1][:46], int(r.n), num(r.var_2comp, 1), num(r.tucker_econ, 3), num(r.tucker_seg, 3), num(r.pct_mismo_cuadrante_vs_rotado_base, 0), num(r.ARI_vs_rotado_base, 2), int(r.n_Q3), num(r.jaccard_Q3_vs_Q3_rotado_base, 2)] for r in sn.itertuples()]
    c.p(f'**Sensibilidad.** Las cargas son prácticamente invariantes a las transformaciones, a la exclusión de los cinco cantones extremos y a los escenarios de año y denominador (congruencia de Tucker ≥ {num(min(sn.tucker_econ.min(), sn.tucker_seg.min()),3)}; {TN("sens")}). La **asignación de cantones** es mucho más sensible: el ARI de los cuadrantes frente a la solución base va de {num(sn.ARI_vs_rotado_base.min(),2)} a {num(sn.ARI_vs_rotado_base[sn.ARI_vs_rotado_base<0.999].max(),2)} (salvo el escenario con población 2023, que reproduce exactamente la clasificación), y el solapamiento de Q3 (índice de Jaccard) va de {num(sn.jaccard_Q3_vs_Q3_rotado_base.min(),2)} a {num(sn.jaccard_Q3_vs_Q3_rotado_base[sn.jaccard_Q3_vs_Q3_rotado_base<0.999].max(),2)}. En la ventana común 2022–2023 (S7), Q3 queda reducido a {int(sn.n_Q3[6])} cantones. El resultado es coherente con la presencia de numerosos cantones cercanos a los umbrales: la **estructura** de dos ejes es robusta; la **lista** de cantones de Q3 no lo es.')
    c.tabla('sens', 'Escenarios de sensibilidad del PCA rotado. Tucker: congruencia de las cargas con las de la solución base; % mismo cuadrante, ARI y Jaccard de Q3: concordancia con la clasificación rotada base en los cantones comunes.',
            ['Escenario', 'n', '% var. 2 comp.', 'Tucker E', 'Tucker S', '% mismo cuad.', 'ARI', 'n Q3', 'Jaccard Q3'], rows, [3300, 450, 850, 800, 800, 900, 650, 600, 850], sz=16)
    # ------------------------------------------------------------ 6.5
    c.h2('6.5 Agrupamiento exploratorio (K-means)')
    sk = T('T06a_seleccion_k'); jc = T('T06e_estabilidad_jaccard').set_index('k'); bs = sk[sk.datos == 'z-score (informe v2)'].set_index('k')
    c.p(f'La solución de K-means con k = 4 reportada en la versión 2 (silhouette {num(K["sil_k4_v2"],3)}; inercia {num(K["inercia_k4_v2"],2)}) correspondía a un óptimo local. Con 300 inicializaciones, el mejor resultado tiene silhouette {num(K["sil_k4_best"],3)} (inercia {num(K["inercia_k4_best"],2)}), con tamaños de 34, 5, 24 y 19 cantones; entre semillas, el silhouette de k = 4 oscila de {num(K["sil_k4_rango_semillas"][0],3)} a {num(K["sil_k4_rango_semillas"][1],3)}. Este valor reemplaza al informado previamente. En ningún caso la separación es fuerte: valores de silhouette alrededor de 0,25 indican estructura débil o no sustancial, y k = 2 ({num(bs.silhouette[2],3)}) y k = 3 ({num(bs.silhouette[3],3)}) superan a k = 4. Con las cinco transformaciones de los datos, el mejor k por silhouette es 2 en cuatro de ellas y 3 en la restante (silhouette máximo entre {num(min(K["sil_max"].values()),2)} y {num(max(K["sil_max"].values()),2)}). La estabilidad por remuestreo es aceptable para k = 2 (Jaccard medio {num(jc.jaccard_medio[2],2)}) y k = 3 ({num(jc.jaccard_medio[3],2)}), y baja para k = 4 ({num(jc.jaccard_medio[4],2)}; mínimo {num(jc.jaccard_min[4],2)}).')
    rows = [[k, num(bs.silhouette[k], 3), num(bs.calinski_harabasz[k], 1), num(bs.davies_bouldin[k], 2), int(bs.tam_min[k]), num(jc.jaccard_medio[k], 2) if k in jc.index else '—'] for k in range(2, 9)]
    c.tabla('kmeans', 'Selección del número de grupos en K-means (variables estandarizadas, n = 82). Silhouette y Calinski–Harabasz: mayor es mejor; Davies–Bouldin: menor es mejor. Jaccard: estabilidad por remuestreo (400 remuestras; solo k = 2 a 6).',
            ['k', 'Silhouette', 'Calinski–Harabasz', 'Davies–Bouldin', 'Tamaño mínimo', 'Jaccard medio'], rows, [900, 1500, 1800, 1700, 1700, 1700], sz=18)
    c.fig('k', 'fig06_seleccion_k', 6.3, 'Selección de k en K-means (2 a 8): silhouette, Calinski–Harabasz, Davies–Bouldin y estabilidad por remuestreo.')
    cx = T('T06c_cruce_cuadrante_rotado_kmeans4'); pc_ = T('T06f_perfil_clusters_kmeans4'); ad = T('T06d_concordancia_ARI_NMI')
    rows = [[r.iloc[0], *[int(x) for x in r.iloc[1:5]]] for _, r in cx.iterrows()]
    c.p(f'La concordancia entre los cuadrantes rotados y los cuatro grupos de K-means es moderada (ARI = {num(K["ari_q_km"],2)}; NMI = {num(K["nmi_q_km"],2)}; prueba de permutación p < 0,001, es decir, mayor que la esperable por azar, pero lejos de coincidir); con los cuadrantes de la versión 2 es similar (ARI = {num(K["ari_qo_km"],2)}; NMI = {num(K["nmi_qo_km"],2)}) y con el agrupamiento jerárquico sobre la distancia de Gower es menor (ARI = {num(K["ari_q_h"],2)}). K-means aísla a cinco cantones extremos (San José, Escazú, Santa Ana, Montes de Oca y Belén) en un grupo de tamaño 5 con valores muy altos de PIB per cápita y unidades jurídicas; en los cuadrantes rotados esos cinco cantones se reparten entre Q1 (Escazú, Santa Ana, Montes de Oca) y Q4 (San José, Belén). La partición de K-means responde sobre todo a la distancia respecto de esos extremos y al gradiente general, mientras que los cuadrantes dependen de dos ejes ortogonales, por lo que ambos métodos no deben verse como confirmación mutua.')
    c.tabla('cruce', 'Tabla cruzada de los cuadrantes rotados (filas) y los grupos de K-means con k = 4 (columnas; solución de 300 inicializaciones). Pureza del agrupamiento respecto del cuadrante: ' + f'{pct(K["pureza_km_vs_q"]*100,0)}.',
            ['Cuadrante rotado', 'Grupo 1', 'Grupo 2', 'Grupo 3', 'Grupo 4'], rows, [2600, 1400, 1400, 1400, 1400], sz=18)
    # ------------------------------------------------------------ 6.6
    c.h2('6.6 Dependencia espacial')
    mo = T('T14_moran_global'); li = T('T15_lisa')
    c.p(f'Todas las variables principales presentan autocorrelación espacial positiva (I de Moran con permutación; q < 0,05 en {S["n_moran_signif"]} de las {S["n_moran_total"]} variables evaluadas; la única excepción es el componente de oferta y tráfico del IVDAC). Para las siete variables el I va de {num(mo.I[:7].min(),2)} (IVDAC) a {num(mo.I[:7].max(),2)} (ICC); para los ejes, {num(S["moran_E"],2)} (económico) y {num(S["moran_S"],2)} (seguridad). Los indicadores de infraestructura más dependientes de la densidad son también los más agrupados (red vial pavimentada, I = {num(mo.I[9],2)}; electricidad por km², I = {num(mo.I[15],2)}). Los cantones de Q3 tienden a ser vecinos entre sí: se observan {int(S["jc_bb"])} uniones Q3–Q3 frente a {num(S["jc_bb_exp"],1)} esperadas bajo aleatoriedad espacial (p = {num(S["jc_bb_p"],3)}). Los cantones, por tanto, no son observaciones independientes, y los valores p de las pruebas de la sección 6.7 se complementan con modelos de error espacial.')
    rows = [[r.variable, num(r.I, 3), num(r.z_sim, 2), pf(r.q_fdr)] for r in mo.iloc[:9].itertuples()]
    c.tabla('moran', 'I de Moran global (contigüidad reina, matriz estandarizada por filas, 9.999 permutaciones) para las siete variables y los dos ejes rotados; q: FDR en la familia de 28 variables (las 28 en el Anexo E). E(I) = −0,012.',
            ['Variable', 'I de Moran', 'z (simulado)', 'q (FDR)'], rows, [3500, 1500, 1500, 1200], sz=18)
    ne = li[(li.eje == 'Eje económico') & (li.cluster_fdr != 'No significativo (FDR)')]
    c.p(f'El análisis local identifica agrupamientos en el eje económico: tras el ajuste por FDR quedan {S["lisa_E_fdr"]} cantones significativos de {S["lisa_E_raw"]} sin ajuste —seis alto-alto (San José, Escazú, Santa Ana, Alajuela, Heredia y Belén) y uno bajo-bajo (Coto Brus)—. En el eje de seguridad ningún cantón es significativo tras el ajuste ({S["lisa_S_raw"]} lo serían sin él). La dependencia espacial es, entonces, marcada para la dimensión económica concentrada en el Valle Central, y más difusa para la seguridad.')
    c.fig('lisa', 'fig09_lisa', 6.3, 'Agrupamientos locales de Moran (LISA) para los ejes económico y de seguridad. Colores intensos: significativos tras FDR; tenues: p < 0,05 sin ajuste.')
    # ------------------------------------------------------------ 6.7
    c.h2('6.7 Ejercicio 2: Q3 frente al resto del país')
    inf = T('T08a_q3rot_vs_resto_infraestructura'); pil = T('T08b_q3rot_vs_resto_pilares'); aI = T('T10a_ajustado_infra'); aP = T('T10b_ajustado_pilares'); dn = T('T09_infra_vs_densidad_poblacional')
    c.p(f'La comparación utiliza Q3 con puntajes rotados (n = {EJ["n_Q3_rot"]}) frente al resto (n = 59). Cinco de los ocho indicadores de infraestructura y conectividad —y los siete pilares del ICC— presentan una diferencia con q < 0,05, con signo opuesto en uno de ellos (llamadas completadas). En la {TN("infra")}, el tamaño de efecto crudo (rank-biserial) es negativo y moderado a grande en red vial pavimentada ({num(inf.rb[0],2)}), sucursales financieras por km² ({num(inf.rb[5],2)}), electricidad por km² ({num(inf.rb[6],2)}) y gasto vial municipal ({num(inf.rb[7],2)}); en llamadas completadas es positivo ({num(inf.rb[3],2)}: valores más altos en Q3); en Internet de hogares es negativo y no robusto a la corrección (q = {num(inf.q_fdr[4],3)}); y en cobertura y velocidad móviles no hay diferencia detectable (q = {num(inf.q_fdr[1],2)} y {num(inf.q_fdr[2],2)}).')
    c.p(f'Para afirmar similitud se aplicó TOST con margen de ±0,5 DE: solo la **cobertura móvil** resulta estadísticamente equivalente entre grupos (p TOST = {num(inf.p_tost[1],3)}; d = {num(inf.d[1],2)}). En velocidad móvil, Internet y el resto de indicadores, la prueba es inconclusa: no hay evidencia suficiente de diferencia, pero tampoco de equivalencia (Anexo D). La afirmación de la versión 2 de que «los indicadores de telecomunicaciones no difieren» se sustituye por esta formulación; y la «brecha» de llamadas completadas va en sentido opuesto al de la hipótesis de rezago.')
    dens_txt = '; '.join(f'{r.variable[0].lower()+r.variable[1:] if not r.variable.startswith(("Viviendas","Red")) else r.variable[0].lower()+r.variable[1:]} {num(r.rho_vs_ln_densidad_poblacional,2)}' for r in dn.itertuples() if r.rho_vs_ln_densidad_poblacional > 0.5)
    c.p(f'**La densidad no es acceso.** Los indicadores de infraestructura que distinguen a Q3 están fuertemente determinados por la densidad poblacional del cantón (ρ de Spearman con el logaritmo de la densidad: {dens_txt}). Q3 tiene una densidad mediana de {num(EJ["med_dens_Q3"],0)} hab./km² frente a {num(EJ["med_dens_resto"],0)} en el resto. Cuando se añaden como controles el logaritmo de la densidad y la región, las diferencias de Q3 en red vial pavimentada ({num(aI.beta_sem[0],2)} DE), sucursales financieras ({num(aI.beta_sem[5],2)}), electricidad por km² ({num(aI.beta_sem[6],2)}) y gasto vial ({num(aI.beta_sem[7],2)}) se aproximan a cero y dejan de ser significativas tras el control de comparaciones múltiples. Persisten las llamadas completadas ({num(aI.beta_sem[3],2)} DE; q = {num(aI.q_sem[3],3)}) y, de forma no concluyente, un menor acceso a Internet ({num(aI.beta_sem[4],2)} DE; q = {num(aI.q_sem[4],3)}). La diferencia cruda entre Q3 y el resto en infraestructura refleja, pues, en gran parte, que Q3 es más rural y menos densamente poblado, y no una brecha específica de infraestructura. Dado que estos indicadores son por unidad de superficie, la conclusión es sobre **densidad territorial**; la medición del **acceso** (por ejemplo, el porcentaje de viviendas con electricidad o la distancia a servicios) requiere otros indicadores.')
    rows = []
    for (r, a) in zip(inf.itertuples(), aI.itertuples()):
        rows.append([r.variable, num(r.med_Q3, 1), num(r.med_resto, 1), f'{num(r.rb,2)} [{num(r.rb_lo,2)}; {num(r.rb_hi,2)}]', pf(r.q_fdr),
                     f'{num(a.beta_sem,2)} [{num(a.lo_sem,2)}; {num(a.hi_sem,2)}]', pf(a.q_sem)])
    c.tabla('infra', 'Q3 (n = 23) frente al resto (n = 59) en ocho indicadores de infraestructura y conectividad (puntajes normalizados 0–100 del ICC; familia F2). Rank-biserial (rb) con IC bootstrap 95% y q (FDR) del contraste crudo; coeficiente de Q3 en DE del indicador, ajustado por ln(densidad) y región con modelo de error espacial (IC 95% y q en la familia F2). Los análisis OLS con errores HC3 dan resultados similares (Anexo D).',
            ['Indicador', 'Mediana Q3', 'Mediana resto', 'rb [IC 95%]', 'q', 'β ajustado (DE) [IC 95%]', 'q ajust.'], rows, [2250, 750, 800, 1700, 850, 1900, 750], sz=16)
    c.fig('forest', 'fig07_forest_q3', 6.0, 'Diferencias entre Q3 y el resto: tamaño de efecto crudo (rank-biserial) y coeficiente ajustado por densidad y región (modelo de error espacial), con intervalos de confianza del 95%.')
    rows = []
    for (r, a) in zip(pil.itertuples(), aP.itertuples()):
        rows.append([r.variable, num(r.med_Q3, 1), num(r.med_resto, 1), f'{num(r.rb,2)} [{num(r.rb_lo,2)}; {num(r.rb_hi,2)}]', pf(r.q_fdr),
                     f'{num(a.beta_sem,2)} [{num(a.lo_sem,2)}; {num(a.hi_sem,2)}]', pf(a.q_sem)])
    od = T('T08d_q3orig_vs_resto_pilares')
    c.p(f'**Pilares del ICC.** Los siete pilares son menores en Q3 (rank-biserial entre {num(pil.rb.min(),2)} y {num(pil.rb.max(),2)}; todos con q < 0,05; {TN("pilares")}), con mayores diferencias en Gobierno ({num(pil.rb[1],2)}), Innovación ({num(pil.rb[5],2)}) y Económico ({num(pil.rb[0],2)}) y la menor en Calidad de vida ({num(pil.rb[6],2)}; q = {num(pil.q_fdr[6],3)}). Este resultado revierte la interpretación de la versión 2, según la cual los pilares económico, laboral y de calidad de vida no distinguían a Q3: con la clasificación sin rotar, el pilar Económico mostraba rb = {num(od.rb[0],2)}, el Laboral {num(od.rb[4],2)} y Calidad de vida {num(od.rb[6],2)}, sin diferencias; esa ausencia era un artefacto de la clasificación. Al ajustar por densidad y región, solo se mantienen con un efecto de magnitud relevante los pilares Económico ({num(aP.beta_sem[0],2)} DE) y Gobierno ({num(aP.beta_sem[1],2)} DE; q = {num(aP.q_sem[0],3)} en ambos), un resultado sugestivo pero no robusto con q > 0,05, y el pilar Laboral (β = {num(aP.beta_sem[4],2)} DE; q = {num(aP.q_sem[4],3)}). Los pilares de Infraestructura, Innovación, Empresarial y Calidad de vida pierden su diferencia.')
    c.tabla('pilares', 'Q3 (n = 23) frente al resto (n = 59) en los siete pilares del ICC (puntaje 0–100; familia F3). Misma estructura que la ' + TN('infra') + '.',
            ['Pilar', 'Mediana Q3', 'Mediana resto', 'rb [IC 95%]', 'q', 'β ajustado (DE) [IC 95%]', 'q ajust.'], rows, [2250, 750, 800, 1700, 850, 1900, 750], sz=16)
    w = T('T13_q3_ponderado_vs_no_ponderado')
    nd = int((w.misma_direccion == 'No').sum())
    c.p(f'**Ponderación por población.** Las diferencias estandarizadas de medias entre Q3 y el resto, con y sin ponderar por población, tienen el mismo sentido en {15-nd} de los 15 indicadores; la excepción es la cobertura móvil, cuya diferencia estandarizada pasa de {num(w.dif_est_no_pond[1],2)} a {num(w.dif_est_pond[1],2)} DE. Con ponderación las brechas viales, financieras, eléctricas y de pilares son más amplias, lo que refleja que los cantones más poblados de Q3 (Pococí, Alajuelita, Sarapiquí y Limón) tienen perfiles distintos de los menos poblados; Alajuelita, con 4.505 hab./km², es un cantón urbano denso y atípico dentro de Q3 (Anexo E). Estos resultados describen cantones, no hogares: no se infiere que los hogares de Q3 tengan menor acceso (falacia ecológica).')
    # LODO
    sq = pd.read_csv(f'{TAB}/T07_ejes_y_cuadrantes_lodo.csv')
    base3 = set(sq.canton[sq.q_rot == 'Q3'])
    def jac(col):
        s = set(sq.canton[sq[col] == 'Q3']); return len(s & base3) / len(s | base3), len(s)
    from sklearn.metrics import adjusted_rand_score as ari
    rows = []
    desc = {'L1': ('Sin ICC (6 variables)', 'q_L1', 'S_L1', 'E_L1'), 'L2': ('Sin IVDAC (6 variables)', 'q_L2', 'S_L2', 'E_L2'), 'L3': ('Sin ISC (6 variables)', 'q_L3', 'S_L3', 'E_L3')}
    rows.append(['Base (7 variables)', '82', '23', '1,00', '1,00', '—', '—', num(P['var12'], 1)])
    for k, (nm, qc, sc, ec) in desc.items():
        j, n3 = jac(qc); cs = np.corrcoef(sq.S, sq[sc])[0, 1]; ce = np.corrcoef(sq.E, sq[ec])[0, 1]
        rows.append([nm, '82', str(n3), num(j, 2), num(ari(sq.q_rot, sq[qc]), 2), num(ce, 2), num(cs, 2), num(EJ[f'var2_{k}'], 1)])
    c.p(f'**Sensibilidad a la circularidad.** Los ejes incluyen al ICC, al ISC y al IVDAC, de modo que se rehízo el análisis excluyendo un dominio a la vez. Con Q3 definido **sin el ICC** (24 cantones; 22 comunes con el Q3 base; Jaccard = {num(EJ["jacc_Q3_rot_L1"],2)}), las diferencias de Q3 en infraestructura y pilares mantienen su sentido y magnitud (Anexo D; por ejemplo, rb = −0,60 en red vial pavimentada y +0,39 en llamadas completadas); las correlaciones de los ejes sin ICC con los ejes base son {num(EJ["r_E_base_E_L1"],2)} (económico) y {num(EJ["r_S_base_S_L1"],2)} (seguridad). Excluir el IVDAC o el ISC modifica más la asignación de cantones (ARI = {num(EJ["ARI_rot_L2"],2)} y {num(EJ["ARI_rot_L3"],2)}), lo que indica que el eje de seguridad depende del par ISC–IVDAC (r entre ambos = −0,78). Por ello, las pruebas de Q3 frente al resto se denominan en lo sucesivo **descomposición descriptiva interna** y no pruebas independientes.')
    c.tabla('lodo', 'Sensibilidad a la exclusión de un dominio a la vez en la construcción de los ejes y los cuadrantes. Jaccard y ARI: concordancia de Q3 y de los cuadrantes con la solución base; r: correlación de los puntajes de cada eje con los de la solución base.',
            ['Escenario', 'n', 'n en Q3', 'Jaccard Q3', 'ARI', 'r eje E', 'r eje S', '% var. 2 comp.'], rows, [2600, 500, 900, 1100, 700, 900, 900, 1300], sz=17)
    c.box('En términos sencillos:', 'el cuadrante Q3 tiene menores puntajes que el resto en casi todos los indicadores de infraestructura y en los siete pilares de competitividad. Pero la mayoría de los indicadores de infraestructura miden cuánta infraestructura hay por kilómetro cuadrado, y esto depende de qué tan poblado esté el cantón. Al comparar cantones de densidad y región similares, esas brechas desaparecen en gran parte. Eso no demuestra que no falte infraestructura en estos cantones: indica que estos indicadores no permiten distinguir entre «hay menos por kilómetro cuadrado porque hay menos gente» y «las personas tienen menos acceso».')
    # ------------------------------------------------------------ 6.8
    c.h2('6.8 Pilares del ICC y componentes del IVDAC frente al eje de seguridad')
    pA = T('T11a_panelA_interno'); pB = T('T11b_panelB_externo'); pE = T('T11c_pilares_vs_eje_economico')
    c.p(f'Dado que el eje de seguridad incluye al ICC y al IVDAC, la correlación del eje completo con sus propios pilares y componentes (panel A) es una **descomposición descriptiva interna**. Para una comparación externa (panel B) se reconstruye el eje sin la familia que se evalúa (sin ICC para los pilares; sin IVDAC para sus componentes). Los dos paneles coinciden en el patrón principal: Innovación, Calidad de vida e Infraestructura se asocian positivamente con el eje de seguridad (panel B: r = {num(pB.r[5],2)}, {num(pB.r[6],2)} y {num(pB.r[3],2)}; q ≤ 0,002), mientras que los pilares Económico ({num(pB.r[0],2)}), Empresarial ({num(pB.r[2],2)}) y Laboral ({num(pB.r[4],2)}) no muestran asociación; el pilar Gobierno es débil y limítrofe (r = {num(pB.r[1],2)}; q = {num(pB.q_fdr[1],3)}). La asociación de Calidad de vida con el eje económico es nula (r = {num(pE.r[12],2)}), lo que sugiere que ese pilar captura una dimensión asociada a seguridad y no a producción.')
    c.p(f'Entre los componentes del IVDAC, en el panel A (eje completo, que incluye al IVDAC), Manifestación de violencia muestra la mayor correlación (r = {num(pA.r[9],2)}), seguida de Demanda ({num(pA.r[8],2)}); en el panel B (eje sin IVDAC) la relación se invierte: Demanda ({num(pB.r[8],2)}) supera a Manifestación ({num(pB.r[9],2)}), con intervalos de confianza que se solapan ({num(pB.lo[8],2)} a {num(pB.hi[8],2)} frente a {num(pB.lo[9],2)} a {num(pB.hi[9],2)}). El componente Oferta y tráfico no se asocia de forma robusta ({num(pB.r[7],2)}; q = {num(pB.q_fdr[7],2)}). La afirmación de la versión 2 de que «pesa más la violencia asociada al tráfico que el consumo» **no se sostiene**: depende de la construcción del eje y las diferencias entre componentes no son estadísticamente distinguibles.')
    rows = []
    for fam, df in [('A · Interno (eje completo)', pA), ('B · Externo (eje sin la familia)', pB)]:
        rows.append(['**' + fam + '**', '', '', ''])
        for r in df.itertuples():
            rows.append([r.variable, f'{num(r.r,2)}', f'{num(r.lo,2)}; {num(r.hi,2)}', pf(r.q_fdr)])
    c.tabla('seg', 'Correlación de Pearson de los pilares del ICC y los componentes del IVDAC con el eje de seguridad (n = 82). Panel A: eje construido con las siete variables (descomposición interna, descriptiva). Panel B: eje construido sin la familia evaluada (comparación externa). IC: bootstrap percentil 95%; q: FDR dentro de cada familia.',
            ['Componente', 'r', 'IC 95%', 'q (FDR)'], rows, [4300, 900, 1700, 1100], sz=17)
    c.fig('seg', 'fig08_eje_seguridad_paneles', 6.0, 'Correlación de once componentes con el eje de seguridad: descomposición interna (gris) y comparación externa (azul), con intervalos de confianza del 95%.')
    # ------------------------------------------------------------ 6.9
    c.h2('6.9 Casos para validación diagnóstica prioritaria dentro de Q3')
    rz = T('T16_rezago_estabilidad_rangos')
    c.p(f'El índice interno de rezago relativo de infraestructura normalizada ordena a los cantones de Q3 de mayor a menor rezago relativo. Su estabilidad se evaluó en {REZ["n_esc"]} escenarios. Con pesos iguales (E0), los cinco primeros son Talamanca, Matina, Hojancha, Buenos Aires y Coto Brus, que coinciden con los cinco primeros por rango mediano; Talamanca figura entre los cinco primeros en {num(REZ["top5_E0_pct"]["Talamanca"],0)}% de los escenarios, Matina en {num(REZ["top5_E0_pct"]["Matina"],0)}%, Hojancha y Buenos Aires en {num(REZ["top5_E0_pct"]["Hojancha"],0)}% y Coto Brus en {num(REZ["top5_E0_pct"]["Coto Brus"],0)}% (Tabla {TABS.index("rezago")+1}). Siquirres tiene un desempeño similar al de Coto Brus ({num(rz.pct_escenarios_top5[5],0)}% de los escenarios). Los cantones del listado de la versión 2 (Talamanca, Nicoya, Osa, Matina y Abangares) cambian porque Nicoya, Osa y Abangares ya no pertenecen a Q3. La concordancia global entre escenarios es moderada (tau de Kendall medio con E0 = {num(REZ["tau_medio_vs_E0"],2)}; mínimo {num(REZ["tau_min"],2)}), por lo que solo los primeros puestos son estables.')
    c.p(f'El índice es, en buena medida, una medida de ruralidad. Su correlación de Spearman con el logaritmo de la densidad poblacional es {num(REZ["E0"]["rho82"],2)} en los 82 cantones y {num(REZ["E0"]["rho_q3"],2)} dentro de Q3 con pesos iguales, y alcanza {num(REZ["E2"]["rho82"],2)} y {num(REZ["E2"]["rho_q3"],2)} con la ponderación por el primer componente. Por esta razón, y por las limitaciones de los indicadores normalizados, los cantones señalados se denominan **casos para validación diagnóstica prioritaria**: son los candidatos a verificar con mediciones físicas de acceso, no cantones donde esté probada una necesidad de intervención ni una prioridad de asignación de recursos.')
    sel = rz.head(12)
    rows = [[int(r.rango_mediano), r.canton, r.provincia, int(r.rango_E0), f'{int(r.rango_min)}–{int(r.rango_max)}', num(r.pct_escenarios_top5, 0) + '%', num(r.indice_E0, 2)] for r in sel.itertuples()]
    c.tabla('rezago', 'Doce cantones de Q3 con mayor rezago relativo según el rango mediano en 13 escenarios (1 = mayor rezago relativo dentro de Q3). E0: pesos iguales; rango mín–máx entre escenarios; % top 5: porcentaje de escenarios en que el cantón está entre los cinco primeros.',
            ['Rango mediano', 'Cantón', 'Provincia', 'Rango E0', 'Rango mín–máx', '% top 5', 'Índice E0'], rows, [1100, 1700, 1500, 1000, 1300, 1000, 1000], sz=17)
    c.fig('rezago', 'fig10_rezago_rangos', 5.4, 'Rangos de los cantones de Q3 con mayor rezago relativo en los 13 escenarios de sensibilidad.')
